---
abstract: 'update your Subversion repository after release'
author:
  - 'Mark Gardner <mjgardner@cpan.org>'
build_requires:
  Capture::Tiny: 0
  Carp: 0
  Dist::Zilla::Plugin::Repository: 0
  Dist::Zilla::Tester: 4.101550
  File::Temp: 0
  SVN::Repos: 0
  Scalar::Util: 0
  Test::Moose: 0
  Test::More: 0.94
  Test::Most: 0
  Text::Template: 0
  blib: 0
  perl: 5.004
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Subversion
requires:
  Cwd: 0
  Dist::Zilla: 4.101550
  Dist::Zilla::Role::AfterRelease: 4.101550
  Dist::Zilla::Role::Plugin: 4.101550
  Dist::Zilla::Role::Releaser: 4.10155
  English: 0
  Modern::Perl: 0
  Moose: 0
  Moose::Role: 0
  MooseX::Types::URI: 0
  Path::Class: 0
  Readonly: 0
  Regexp::DefaultFlags: 0
  SVN::Client: 0
  SVN::Wc: 0
  namespace::autoclean: 0
  perl: 5.010
  strict: 0
  utf8: 0
resources:
  bugtracker: https://github.com/mjgardner/Dist-Zilla-Plugin-Subversion/issues
  homepage: http://search.cpan.org/dist/Dist-Zilla-Plugin-Subversion/
  repository: git://github.com/mjgardner/Dist-Zilla-Plugin-Subversion.git
version: 1.101591
